// Menu Insude

using Serenity.Navigation;
using MyPages = MiMovieTutorial.INSUDE.Pages;

[assembly: NavigationMenu(10000, "INSUDE", icon: "fa-anchor")] 
//[assembly: NavigationLink(10000, "INSUDE/Indices", typeof(MyPages.IndicesController), icon: "fa-desktop")]
[assembly: NavigationLink(10000, "INSUDE/Alumnos", typeof(MyPages.AlumnosController), icon: "fa-user-graduate")]
[assembly: NavigationMenu(10000, "INSUDE/Registro", icon: "fa-anchor")]
[assembly: NavigationLink(10000, "INSUDE/Registro/Calificaciones por Alumnos", typeof(MyPages.IndicesController), icon: "fa-desktop")]
[assembly: NavigationLink(10000, "INSUDE/Registro/Calificaciones por Materias", typeof(MyPages.IndicesController), icon: "fa-desktop")]
[assembly: NavigationLink(10000, "INSUDE/Registro/Válida Calificaciones Materias", typeof(MyPages.IndicesController), icon: "fa-desktop")]
[assembly: NavigationMenu(10000, "INSUDE/Servicios Estudiantiles",  icon: "fa-anchor")]
[assembly: NavigationLink(10000, "INSUDE/Servicios Estudiantiles/Solicitar Servicio", typeof(MyPages.IndicesController), icon: "fa-desktop")]
[assembly: NavigationMenu(10000, "INSUDE/Configuración", icon: "fa-anchor")]
[assembly: NavigationLink(10000, "INSUDE/Configuración/Facultades", typeof(MyPages.FacultadesController), icon: "fa-desktop")]
[assembly: NavigationLink(10000, "INSUDE/Configuración/Escuelas", typeof(MyPages.EscuelasController), icon: "fa-desktop")]
[assembly: NavigationLink(10000, "INSUDE/Configuración/Docentes", typeof(MyPages.InstructoresController), icon: "fa-desktop")]
[assembly: NavigationLink(10000, "INSUDE/Configuración/Carreras", typeof(MyPages.TitulosController), icon: "fa-desktop")]
[assembly: NavigationLink(10000, "INSUDE/Configuración/Pensum", typeof(MyPages.PensumController), icon: "fa-desktop")]
[assembly: NavigationLink(10000, "INSUDE/Configuración/Promociones", typeof(MyPages.PromocionesController), icon: "fa-desktop")]
[assembly: NavigationLink(10000, "INSUDE/Configuración/Materias", typeof(MyPages.MateriasController), icon: "fa-desktop")]
[assembly: NavigationLink(10000, "INSUDE/Configuración/Requisitos", typeof(MyPages.RequisitosController), icon: "fa-desktop")]
[assembly: NavigationLink(10000, "INSUDE/Configuración/Tipo de Califcación", typeof(MyPages.TipoDeCalificacionController), icon: "fa-desktop")]
[assembly: NavigationLink(10000, "INSUDE/Configuración/Niveles por Carrera", typeof(MyPages.NivelesPorCarreraController), icon: "fa-desktop")]
[assembly: NavigationLink(10000, "INSUDE/Configuración/Rangos", typeof(MyPages.RangosController), icon: "fa-desktop")]
[assembly: NavigationLink(10000, "INSUDE/Configuración/Servicios Estudiantiles", typeof(MyPages.ServiciosEstudiantilesController), icon: "fa-desktop")]
[assembly: NavigationLink(10000, "INSUDE/Configuración/Paises", typeof(MyPages.PaisController), icon: "fa-desktop")]
[assembly: NavigationMenu(10000, "INSUDE/Reportes", icon: "fa-anchor")]
[assembly: NavigationLink(10000, "INSUDE/Reportes/Listado de Alumnos", typeof(MyPages.IndicesController), icon: "fa-desktop")]
[assembly: NavigationLink(10000, "INSUDE/Reportes/Otros", typeof(MyPages.IndicesController), icon: "fa-desktop")]
[assembly: NavigationMenu(10000, "INSUDE/Estadísticas",  icon: "fa-anchor")]
[assembly: NavigationLink(10000, "INSUDE/Estadísticas/Generales", typeof(MyPages.IndicesController), icon: "fa-desktop")]
[assembly: NavigationLink(10000, "INSUDE/Estadísticas/Población de Alumnos", typeof(MyPages.IndicesController), icon: "fa-desktop")]
[assembly: NavigationMenu(10000, "INSUDE/Educación Continua", icon: "fa-anchor")]
[assembly: NavigationLink(10000, "INSUDE/Educación Continua/Menu1", typeof(MyPages.IndicesController), icon: "fa-desktop")]
[assembly: NavigationLink(10000, "INSUDE/Educación Continua/Menu2", typeof(MyPages.IndicesController), icon: "fa-desktop")]
[assembly: NavigationLink(10000, "INSUDE/Educación Continua/Menu3", typeof(MyPages.IndicesController), icon: "fa-desktop")]
[assembly: NavigationLink(10000, "INSUDE/Educación Continua/Menu4", typeof(MyPages.IndicesController), icon: "fa-desktop")]
[assembly: NavigationMenu(10000, "INSUDE/Seguridad",icon: "fa-anchorna")]
[assembly: NavigationLink(10000, "INSUDE/Seguridad/Perfiles", typeof(MyPages.PrivilegiosController), icon: "fa-desktop")]
[assembly: NavigationLink(10000, "INSUDE/Seguridad/Privilegios", typeof(MyPages.IndicesController), icon: "fa-desktop")]
[assembly: NavigationLink(10000, "INSUDE/Seguridad/Usuarios", typeof(MyPages.IndicesController), icon: "fa-desktop")]
[assembly: NavigationLink(10000, "INSUDE/Seguridad/Auditoría", typeof(MyPages.IndicesController), icon: "fa-desktop")]
[assembly: NavigationMenu(10000, "INSUDE/Auxiliares", icon: "fa-anchorna")]
[assembly: NavigationLink(10000, "INSUDE/Auxiliares/Dependencias", typeof(MyPages.DependenciasController), icon: "fa-desktop")]
[assembly: NavigationLink(10000, "INSUDE/Auxiliares/Estado Civil", typeof(MyPages.EstadocivilController), icon: "fa-desktop")]
[assembly: NavigationLink(10000, "INSUDE/Auxiliares/Nacionalidad", typeof(MyPages.NacionalidadController), icon: "fa-desktop")]
[assembly: NavigationLink(10000, "INSUDE/Auxiliares/Sexo", typeof(MyPages.SexoController), icon: "fa-desktop")]
[assembly: NavigationLink(10000, "INSUDE/Auxiliares/Alumnos Carreras", typeof(MyPages.AlumnosCarrerasController), icon: "fa-desktop")]
[assembly: NavigationLink(10000, "INSUDE/Auxiliares/Alumnos Familiares", typeof(MyPages.AlumnosFamiliaresController), icon: "fa-desktop")]
//[assembly: NavigationLink(10000, "INSUDE/Auxiliares/Almacenes", typeof(MyPages.MalmacenController), icon: "fa-desktop")]
//[assembly: NavigationLink(10000, "INSUDE/Auxiliares/Articulos", typeof(MyPages.MproductController), icon: "fa-desktop")]
[assembly: NavigationLink(10000, "INSUDE/Auxiliares/Compania", typeof(MyPages.CompaniaController), icon: "fa-desktop")]
//[assembly: NavigationLink(10000, "INSUDE/Auxiliares/Existencia", typeof(MyPages.ExistencialmaController), icon: null)]
[assembly: NavigationMenu(10000, "INSUDE/Ayuda", icon: "fa-desktop")]
//[assembly: NavigationLink(int.MaxValue, "INSUDE/Status", typeof(MyPages.StatusController), icon: null)]